---
title: "GLIS Template5 Checks"
author: "Jeremy Holden"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rprocval)
library(RODBC)
library(lakeontario)
library(usethis)
library(tidyr)
library(dplyr)
library(purrr)
library(ggplot2)

load("params.RData")
dbase <- file.path(paste0("Data/Processed/", prj_params$PRJ_CD, "_T5.accdb"))
```

# `r prj_params$PRJ_CD`

## Connect to raw data
```{r}
conn <- odbcConnectAccess2007(dbase, uid = "", pwd = "")
FN011 <- sqlFetch(conn, "FN011")
FN012 <- sqlFetch(conn, "FN012")
FN022 <- sqlFetch(conn, "FN022")
FN026 <- sqlFetch(conn, "FN026")
FN026_Subspace <- sqlFetch(conn, "FN026_Subspace")
FN028 <- sqlFetch(conn, "FN028")
FN121 <- sqlFetch(conn, "FN121")
FN123 <- sqlFetch(conn, "FN123")
FN124 <- sqlFetch(conn, "FN124")
FN125 <- sqlFetch(conn, "FN125")
odbcClose(conn)
```

## `rprocval` checks
```{r}
fn121_column_check_t5(FN121)
fn123_column_check(FN123)
fn121_error_queries_t5(FN121, FN123)
fn123_error_queries(FN123, FN125)
fn_template5_basic_checks(FN012, FN022, FN026_Subspace, FN028, FN121, FN123, FN124, FN125)
fn124_minmax <- fn124_minmax_TLEN(FN124, FN012)
fulton_errors <- fn125_fulton(FN125, FN012)
lengtherrors125 <- fn125_minmax_TLEN(FN125, FN012)
```

```{r}
FN125_errors <- FN125 %>%
  split(.$SPC) %>%
  map(fn125_tl_rwt_lm, makeplot = T) %>%
  bind_rows()
```

